//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormPimpMyUnicorn.WCFPimpMyUnicorn {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPimpMyUnicorn.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDatabase", ReplyAction="http://tempuri.org/IService1/UpdateDatabaseResponse")]
        bool UpdateDatabase(string[] queries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDatabase", ReplyAction="http://tempuri.org/IService1/UpdateDatabaseResponse")]
        System.Threading.Tasks.Task<bool> UpdateDatabaseAsync(string[] queries);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WinFormPimpMyUnicorn.WCFPimpMyUnicorn.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WinFormPimpMyUnicorn.WCFPimpMyUnicorn.IService1>, WinFormPimpMyUnicorn.WCFPimpMyUnicorn.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateDatabase(string[] queries) {
            return base.Channel.UpdateDatabase(queries);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDatabaseAsync(string[] queries) {
            return base.Channel.UpdateDatabaseAsync(queries);
        }
    }
}
